# Generated by Django 5.2.6 on 2025-09-20 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('cache_type', models.CharField(choices=[('metric_result', 'Metric Calculation Result'), ('report_data', 'Report Data'), ('aggregated_data', 'Aggregated Data'), ('ml_prediction', 'ML Prediction Result'), ('trend_analysis', 'Trend Analysis'), ('comparative_data', 'Comparative Analysis Data')], max_length=50)),
                ('data', models.JSONField(help_text='Cached data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Cache metadata (source, parameters, etc.)')),
                ('expires_at', models.DateTimeField()),
                ('hit_count', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('data_size', models.IntegerField(blank=True, help_text='Size of cached data in bytes', null=True)),
                ('source_metric_id', models.UUIDField(blank=True, help_text='Reference to metric_definitions.id if applicable', null=True)),
            ],
            options={
                'db_table': 'analytics.analytics_cache',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cache_key'], name='analytics.a_cache_k_033971_idx'), models.Index(fields=['cache_type'], name='analytics.a_cache_t_ad5219_idx'), models.Index(fields=['expires_at'], name='analytics.a_expires_110ff1_idx'), models.Index(fields=['source_metric_id'], name='analytics.a_source__c073b2_idx'), models.Index(fields=['last_accessed'], name='analytics.a_last_ac_8793b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(help_text='Detailed description of what this metric measures')),
                ('calculation_method', models.CharField(choices=[('sum', 'Sum'), ('avg', 'Average'), ('count', 'Count'), ('percentage', 'Percentage'), ('ratio', 'Ratio'), ('growth_rate', 'Growth Rate'), ('trend', 'Trend Analysis'), ('correlation', 'Correlation'), ('standard_deviation', 'Standard Deviation'), ('min', 'Minimum'), ('max', 'Maximum'), ('median', 'Median'), ('custom', 'Custom Formula')], max_length=50)),
                ('category', models.CharField(choices=[('productivity', 'Productivity'), ('code_quality', 'Code Quality'), ('performance', 'Performance'), ('collaboration', 'Collaboration'), ('time_tracking', 'Time Tracking'), ('git_activity', 'Git Activity'), ('deployment', 'Deployment'), ('security', 'Security'), ('testing', 'Testing'), ('documentation', 'Documentation')], default='productivity', max_length=50)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON configuration for metric calculation (formulas, filters, etc.)')),
                ('data_sources', models.JSONField(blank=True, default=list, help_text='List of data sources this metric depends on (monitoring, management, etc.)')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (hours, %, count, etc.)', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_ml', models.BooleanField(default=False, help_text='Whether this metric requires ML processing')),
                ('cache_duration', models.IntegerField(default=300, help_text='Cache duration in seconds')),
            ],
            options={
                'db_table': 'analytics.metric_definitions',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['name'], name='analytics.m_name_0fc87f_idx'), models.Index(fields=['category'], name='analytics.m_categor_b29ce5_idx'), models.Index(fields=['calculation_method'], name='analytics.m_calcula_b6d501_idx'), models.Index(fields=['is_active'], name='analytics.m_is_acti_f904fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('productivity', 'Productivity Report'), ('code_quality', 'Code Quality Report'), ('time_tracking', 'Time Tracking Report'), ('team_performance', 'Team Performance Report'), ('individual_performance', 'Individual Performance Report'), ('project_summary', 'Project Summary Report'), ('git_activity', 'Git Activity Report'), ('deployment_metrics', 'Deployment Metrics Report'), ('custom', 'Custom Report'), ('comparative', 'Comparative Analysis'), ('trend_analysis', 'Trend Analysis'), ('anomaly_detection', 'Anomaly Detection Report')], max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Report configuration including filters, date ranges, metrics, etc.')),
                ('created_by', models.UUIDField(help_text='Reference to auth.users.id')),
                ('company_id', models.UUIDField(blank=True, help_text='Reference to auth.companies.id', null=True)),
                ('team_id', models.UUIDField(blank=True, help_text='Reference to management.teams.id', null=True)),
                ('project_id', models.UUIDField(blank=True, help_text='Reference to management.projects.id', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel')], default='json', max_length=10)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to generated report file', max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('data', models.JSONField(blank=True, help_text='Report data (for JSON reports)', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time', models.DecimalField(blank=True, decimal_places=3, help_text='Execution time in seconds', max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this report expires', null=True)),
            ],
            options={
                'db_table': 'analytics.reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='analytics.r_created_9859d6_idx'), models.Index(fields=['company_id'], name='analytics.r_company_4eade5_idx'), models.Index(fields=['team_id'], name='analytics.r_team_id_07ad55_idx'), models.Index(fields=['project_id'], name='analytics.r_project_634ad2_idx'), models.Index(fields=['type'], name='analytics.r_type_3dcf36_idx'), models.Index(fields=['status'], name='analytics.r_status_e33acc_idx'), models.Index(fields=['created_at'], name='analytics.r_created_6b7c5f_idx'), models.Index(fields=['expires_at'], name='analytics.r_expires_f8fd32_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measurement', models.CharField(help_text="Measurement name (e.g., 'code_commits', 'build_duration')", max_length=255)),
                ('source', models.CharField(help_text="Data source (e.g., 'github', 'jenkins', 'jira')", max_length=255)),
                ('timestamp', models.DateTimeField(help_text='When the measurement was taken')),
                ('value_float', models.FloatField(blank=True, help_text='Numeric value', null=True)),
                ('value_int', models.BigIntegerField(blank=True, help_text='Integer value', null=True)),
                ('value_string', models.TextField(blank=True, help_text='String value', null=True)),
                ('value_bool', models.BooleanField(blank=True, help_text='Boolean value', null=True)),
                ('tags', models.JSONField(default=dict, help_text="Tags as key-value pairs (e.g., {'user': 'john', 'repo': 'myproject'})")),
                ('fields', models.JSONField(default=dict, help_text='Additional field data')),
                ('user_id', models.CharField(blank=True, help_text='User ID if applicable', max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, help_text='Project ID if applicable', max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, help_text='Team ID if applicable', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics.time_series_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['measurement', 'timestamp'], name='analytics.t_measure_ca6e56_idx'), models.Index(fields=['source', 'timestamp'], name='analytics.t_source_aceab8_idx'), models.Index(fields=['user_id', 'timestamp'], name='analytics.t_user_id_f510c9_idx'), models.Index(fields=['project_id', 'timestamp'], name='analytics.t_project_7e4faa_idx'), models.Index(fields=['team_id', 'timestamp'], name='analytics.t_team_id_8cd44b_idx'), models.Index(fields=['timestamp'], name='analytics.t_timesta_5ae1c9_idx'), models.Index(fields=['measurement', 'source'], name='analytics.t_measure_849f3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(choices=[('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('eq', 'Equal to'), ('ne', 'Not equal to'), ('change_gt', 'Change greater than'), ('change_lt', 'Change less than'), ('trend_up', 'Trending upward'), ('trend_down', 'Trending downward')], max_length=20)),
                ('threshold_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notification_config', models.JSONField(blank=True, default=dict, help_text='Notification configuration (emails, webhooks, etc.)')),
                ('context_filters', models.JSONField(blank=True, default=dict, help_text='Context filters for when this rule applies')),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Cooldown period before re-triggering')),
                ('metric_definition', models.ForeignKey(db_column='metric_definition_id', on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='analytics.metricdefinition')),
            ],
            options={
                'db_table': 'analytics.alert_rules',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['metric_definition'], name='analytics.a_metric__4b656a_idx'), models.Index(fields=['is_active'], name='analytics.a_is_acti_53066b_idx'), models.Index(fields=['severity'], name='analytics.a_severit_e4196c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_time', models.DateTimeField(help_text='When this snapshot was taken')),
                ('period_start', models.DateTimeField(help_text='Start of the measurement period')),
                ('period_end', models.DateTimeField(help_text='End of the measurement period')),
                ('value', models.DecimalField(decimal_places=6, help_text='Calculated metric value', max_digits=20)),
                ('raw_data_count', models.IntegerField(help_text='Number of data points used in calculation')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('calculation_metadata', models.JSONField(default=dict, help_text='Additional calculation details')),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence in the calculation (0-1)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='analytics.metricdefinition')),
            ],
            options={
                'db_table': 'analytics.metric_snapshots',
                'ordering': ['-snapshot_time'],
                'indexes': [models.Index(fields=['metric_definition', 'snapshot_time'], name='analytics.m_metric__19ef62_idx'), models.Index(fields=['user_id', 'snapshot_time'], name='analytics.m_user_id_a94f3c_idx'), models.Index(fields=['project_id', 'snapshot_time'], name='analytics.m_project_7e664e_idx'), models.Index(fields=['team_id', 'snapshot_time'], name='analytics.m_team_id_30fc83_idx'), models.Index(fields=['period_start', 'period_end'], name='analytics.m_period__951d20_idx')],
                'unique_together': {('metric_definition', 'snapshot_time', 'user_id', 'project_id', 'team_id')},
            },
        ),
    ]
