# Generated by Django 4.2.16 on 2025-09-27 02:34
# Manual fix for django_admin_log.user_id type mismatch with Django's default User model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_rename_alert_rules_metric_idx_analytics_a_metric__4b656a_idx_and_more'),
    ]

    operations = [
        # Clear the admin log table to avoid conversion issues
        migrations.RunSQL(
            sql="DELETE FROM django_admin_log;",
            reverse_sql="-- Cannot reverse deletion"
        ),

        # Drop any existing foreign key constraint
        migrations.RunSQL(
            sql="ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey CASCADE;",
            reverse_sql="-- Reverse not needed"
        ),

        # Change the user_id column type from UUID to integer to match auth_user.id
        migrations.RunSQL(
            sql="""
            ALTER TABLE django_admin_log
            ALTER COLUMN user_id TYPE integer USING NULL;
            """,
            reverse_sql="""
            ALTER TABLE django_admin_log
            ALTER COLUMN user_id TYPE UUID;
            """
        ),

        # Re-add the foreign key constraint to Django's auth_user table
        migrations.RunSQL(
            sql="""
            ALTER TABLE django_admin_log
            ADD CONSTRAINT django_admin_log_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES auth_user(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            ALTER TABLE django_admin_log
            DROP CONSTRAINT django_admin_log_user_id_fkey;
            """
        ),
    ]
