# Generated by Django 4.2.16 on 2025-09-27 04:52
# Revert the incorrect admin log fix that conflicts with auth service UUID users

from django.db import migrations, connection


def revert_admin_log_fix(apps, schema_editor):
    """
    Revert the incorrect admin log fix that converted UUID back to integer.
    Only applies in production where services share the same database.
    In CI/test environments, skip this migration since each service is isolated.
    """
    if connection.vendor != 'postgresql':
        return

    with connection.cursor() as cursor:
        # Check if we're in a production environment with auth.users table
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'auth' AND table_name = 'users'
            );
        """)
        auth_users_exists = cursor.fetchone()[0]

        if not auth_users_exists:
            # In CI/test environment - skip this migration
            # Each service has its own isolated User model
            return

        # Check current type - might be integer from previous migration 0004
        cursor.execute("""
            SELECT data_type FROM information_schema.columns
            WHERE table_name = 'django_admin_log' AND column_name = 'user_id'
        """)
        current_type = cursor.fetchone()

        if current_type and current_type[0] == 'integer':
            # Clear existing data to avoid conversion issues
            cursor.execute("DELETE FROM django_admin_log;")

            # Drop constraint
            cursor.execute("ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey CASCADE;")

            # Convert back to UUID to match auth service setup - use proper USING clause
            cursor.execute("ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE UUID USING NULL;")

            # Add constraint to auth.users table (UUID PKs)
            cursor.execute("""
                ALTER TABLE django_admin_log
                ADD CONSTRAINT django_admin_log_user_id_fkey
                FOREIGN KEY (user_id) REFERENCES auth.users(id)
                ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
            """)


def reverse_revert_admin_log_fix(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20250926_2234'),
    ]

    operations = [
        migrations.RunPython(
            revert_admin_log_fix,
            reverse_revert_admin_log_fix,
        ),
    ]
