# Generated by Django 4.2.16 on 2025-09-27 02:34
# Manual fix for django_admin_log.user_id type mismatch with Django's default User model

from django.db import connection, migrations


def fix_admin_log_user_id_postgresql(apps, schema_editor):
    """
    Fix django_admin_log.user_id type to match auth_user.id (PostgreSQL only)
    """
    # Only run on PostgreSQL - SQLite tests don't need this
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        # Clear existing data to avoid conversion issues
        cursor.execute("DELETE FROM django_admin_log;")

        # Drop foreign key constraint
        cursor.execute(
            "ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fkey CASCADE;"
        )

        # Change column type from UUID to integer
        cursor.execute(
            "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE integer USING NULL;"
        )

        # Re-add foreign key constraint
        cursor.execute(
            """
            ALTER TABLE django_admin_log
            ADD CONSTRAINT django_admin_log_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES auth_user(id)
            ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
        """
        )


def reverse_fix_admin_log_user_id_postgresql(apps, schema_editor):
    """Reverse operation - not implemented"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0003_rename_alert_rules_metric_idx_analytics_a_metric__4b656a_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            fix_admin_log_user_id_postgresql,
            reverse_fix_admin_log_user_id_postgresql,
        ),
    ]
